name: wolfSSL CI tests
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
    docker-Espressif:
        uses: ./.github/workflows/docker-Espressif.yml
    multi-compiler:
        uses: ./.github/workflows/multi-compiler.yml
    docker-OpenWrt:
        uses: ./.github/workflows/docker-OpenWrt.yml
    os-check:
        uses: ./.github/workflows/os-check.yml
    osp:
        uses: ./.github/workflows/osp-check.yml
